---
title       : Slidify 
subtitle    : Data Prsentation
author      : Pratik Chhapolika
job         : Coursera Project
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
github: 
            user: pratikchhapolika 
            repo: slidify
---
## Slide 2
```{r simple-plot, fig.height = 6, fig.align = 'center', message = F}
 require(ggplot2)
 qplot(wt, mpg, data = mtcars)
 
```

---

# Storm Database Explorer

```{r, echo=FALSE}
library(data.table)
library(rCharts)
library(reshape2)

dt <- fread('events.agg.csv')
dt.agg.year <- dt[, list(Count=sum(COUNT), Injuries=sum(INJURIES), Fatalities=sum(FATALITIES)), by=list(YEAR)]
```

---

## Between 1950 and 2011 severe weather events caused at least

 - `r format(sum(dt$FATALITIES), big.mark=' ')` deaths
 - `r format(sum(dt$INJURIES), big.mark=' ')` injuries
 - $`r format(round((sum(dt$PROPDMG) + sum(dt$CROPDMG)) / 1000), big.mark=' ')` billion worth of damage
 

---

## ... and it can generate cool plots


```{r nvd3plot2, results = 'asis', comment = NA, message = F, echo = F} 

data <- melt(dt.agg.year[, list(YEAR=YEAR, Injuries=Injuries, Fatalities=Fatalities)], id='YEAR')
populationImpact <- nPlot(
    value ~ YEAR, group = 'variable', data = data[order(-YEAR, variable, decreasing = T)],
    type = 'stackedAreaChart', dom = 'populationImpact'
)
        
populationImpact$chart(margin = list(left = 100))
populationImpact$yAxis( axisLabel = "Affected", width = 80)
populationImpact$xAxis( axisLabel = "Year", width = 70)
        
populationImpact
```
 
 




